deploy_pubspec:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_APPROVED'
  stage: deploy
  before_script:
#    - git config --bool core.bare true
    - git config user.name "Gitlab CI"
    - git config user.email "noreply@swivt.com.np"
    - git checkout $CI_COMMIT_REF_NAME
    - git reset --hard
    - git status
    - git pull
    - perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
    - git add pubspec.yaml
    - git commit -m "version upgraded."
    - git push
  script:
    - dart pub publish -f
  after_script:
#    - git config remote.ssh-origin.url >&- || git remote add ssh-origin git@gitlab.com:swivt/super-module.git
#    - git add pubspec.yaml
#    - git commit -m "version upgraded."
#    - git push ssh-origin $CI_COMMIT_REF_NAME
  tags:
    - dart