deploy_pubspec:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_APPROVED'
  stage: deploy
  before_script:
    - perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
  script:
    - dart pub publish -f
  after_script:
    - git add pubspec.yaml
    - git config user.name "Gitlab CI"
    - git config user.email "noreply@swivt.com.np"
    - git commit -m "version upgraded."
    - git config remote.ssh-origin.url >&- || git remote add ssh-origin git@gitlab.com:swivt/super-module.git
    - git push ssh-origin HEAD:develop
  tags:
    - dart