deploy_pubspec:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_APPROVED'
  stage: deploy
  before_script:
#    - git config --bool core.bare true
#    - git config receive.denyCurrentBranch ignore
    - git config user.name "gitlab-ci"
    - git config user.email "app@swivt.com.np"
    - git clone git@gitlab.com:swivt/super-module.git
    - cd super-module
#    - git checkout $CI_COMMIT_REF_NAME
    - git fetch
    - git checkout $CI_COMMIT_REF_NAME
#    - git pull
    - perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
    - git add pubspec.yaml
    - git status
    - git commit -m "version upgraded."
#    - git config --bool core.bare true
    - git push origin HEAD:$CI_COMMIT_REF_NAME
  script:
    - perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
    - dart pub publish -f
#  after_script:
#    - git config remote.ssh-origin.url >&- || git remote add ssh-origin git@gitlab.com:swivt/super-module.git
#    - git add pubspec.yaml
#    - git commit -m "version upgraded."
#    - git push ssh-origin $CI_COMMIT_REF_NAME
  tags:
    - dart