name: super_module
description: AuthModule
version: 1.0.0+1
authors:
  - Nikesh Maharjan

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  local_auth: 1.1.6
  flutter_easyloading: ^3.0.0
  jwt_decode: ^0.2.0
  flutter_secure_storage: ^4.2.0
  google_sign_in:
  json_serializable: 3.5.1
  data_connection_checker: ^0.3.4
  injectable: 1.0.7
  get_it: ^5.0.1
  flutter_bloc:
  pointycastle: ^2.0.1
  asn1lib: ^1.0.2
  sign_in_with_apple: ^3.0.0
  flutter_facebook_auth: ^3.3.3-no-nullsafety

  rest_client:
    path: ../rest_client


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.11.0
  injectable_generator: 1.0.7
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launcher_icon.png"

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.waihat.authmodule.super_module
    iosBundleIdentifier: com.waihat.authmodule.authModule
