#!/bin/bash
set -e
#perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' pubspec.yaml
perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)(\+)(\d+)$/$1.($2+1).$3.($4+1)/e' pubspec.yaml
#version=bspe`grep 'version: ' pubspec.yaml | sed 's/version: //'`
#git commit -m "Bump version to $version" pubspec.yaml
#git tag $version