#!/bin/bash
set -e
perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($2+1)/e' client/pubspec.yaml

# Commit and tag this change.
version=bspe`grep 'version: ' client/puc.yaml | sed 's/version: //'`
git commit -m "Bump version to $version" client/pubspec.yaml
git tag $version